name: CI
on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 6 * * *"


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: f
        run: |
          git clone https://gitlab.com/sulix/devel/sources/ymp ymp
          cd ymp
          echo "deb https://deb.debian.org/debian unstable main contrib" | sudo tee /etc/apt/sources.list
          sudo apt update --allow-insecure-repositories
          sudo apt install debian-archive-keyring --allow-unauthenticated
          sudo apt update --allow-insecure-repositories
          sudo apt install meson gcc valac --no-install-recommends -yq
          sudo apt install libarchive-dev libreadline-dev libcurl4-openssl-dev libbrotli-dev --no-install-recommends -yq
          meson build -Ddebug=true -Dtools=true -Dlibbrotli=false -Dshared=true --prefix=/usr
          sudo ninja -C build install
          sudo ymp bootstrap --mirror='https://gitlab.com/sulix/packages/binary-repo/-/raw/master/$uri' --destdir='rootfs' --no-emerge @sys --no-processbar
