name: CI
on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 6 * * *"


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: f
        run: |
          git clone https://gitlab.com/sulix/devel/sources/ymp ymp
          cd ymp
          sudo apt update
          sudo apt full-upgrade -y
          sudo apt install meson gcc valac --no-install-recommends -y
          sudo apt install libarchive-dev libreadline-dev libcurl4-openssl-dev libbrotli-dev --no-install-recommends -y
          meson build -Ddebug=true -Dtools=true -Dlibbrotli=false -Dshared=true --prefix=/usr
          sudo ninja -C build install
          ymp bootstrap --mirror='https://gitlab.com/sulix/packages/binary-repo/-/raw/master/$uri' --destdir='rootfs' --no-emerge @sys
